# Generated by Django 3.2.15 on 2022-08-14 14:06

import cloudinary.models
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('twitter', models.CharField(max_length=30)),
                ('github', models.CharField(max_length=30)),
                ('linkedin', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('profession', models.TextField(max_length=400)),
                ('skills', models.TextField(max_length=400)),
                ('engage_me', models.TextField(max_length=400)),
                ('about_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('languages', multiselectfield.db.fields.MultiSelectField(choices=[('html', 'HTML-5'), ('css', 'CSS-3'), ('python', 'Python'), ('javascript', 'JavaScript'), ('django', 'Django'), ('flask', 'Flask'), ('bootstrap', 'Bootstrap')], max_length=49)),
                ('project_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('excerpt', models.TextField(blank=True, max_length=550)),
                ('github_link', models.CharField(max_length=200)),
                ('host_link', models.CharField(max_length=200)),
            ],
        ),
    ]
